<?php
    // Construct new Pt Service Object
    $ptService = new Service_Pt();
    // Construct new Adm Service Object
    $admService = new Service_Adm();
?>

<script type="text/javascript">

    // Load the data into the PAS.data object
    DATA.reg = <?php echo $ptService->getJson($this->patientId); ?>;
    DATA.adm = <?php echo $admService->getJson($this->admId); ?>;
    DATA.newAdm = {

        "ptInfo": {

            "uniqueId": <?= $this->patientId;?>,
            "confidential": null,
            "currentIns": null,
            "diagnosis": null,
            "admNum": null
        },

        "admDetails": {

            "admType": null,
            "date": null,
            "time": null,
            "length": null,
            "admId": null
        },

        "md": {

            "admitting": null,
            "attending": null,
            "surgical": null,
            "referring": null,
            "referringId": null
        },

        "location": {

            "specialty": null,
            "ward": null,
            "roomNumber": null,
            "bedNumber": null
        },

        "status": {

            "ptStatus": "Scheduled",
            "admDate": null,
            "admTime": null,
            "dcDate": null,
            "dcTime": null,
            "dcNotes": null
        },

        "notes": {

            "authorization": null,
            "reminderNotes": null,
            "equipment": null,
            "facility": null,
            "staff": null
        }
    };
    DATA.admList = <?= $admService->getAdmListForPtJson( $this->patientId ); ?>;
    DATA.query = '<?= $this->searchTerms; ?>';
    DATA.searchTerms = '<?= $this->searchTerms; ?>';
</script>

<!-- AngularJS services for patient file -->
<script type="text/javascript" src="/js/services/serv-patient.js"></script>

<!-- AngularJS controllers for patient file -->
<script type="text/javascript" src="/js/controllers/ctrlr-patient.js"></script>

<div id="sectionContent" class="row-fluid tabContainer" role="main" ng-controller="PAS.ctrlr.patient">

<?= $this->ptsActionsNav(); ?>

<!-- Imports from views > helpers PtsSidebar.php -->
<!-- This handles what sidebar to use -->
<?= $this->ptsSidebar(); ?>

    <section id="mainPanel" class="<?= $this->mainPanelWidth; ?> parent">

    <!-- This imports the header, patient file navigation and the alert elements -->
    <?= $this->ptsHeader(); ?>

        <section id="patientInfoContainer" class="tabContainer">

            <form name="admsTabForm">

                <fieldset class="row-fluid">

                    <legend>Scheduled</legend>

                    <p class="formInstructions span9">
                        To edit an admission, just click on an admission below.
                    </p><!-- Remove whitespace

                 --><a href="<?= $this->urlNew; ?>" class="newButton span3 no-padding">
                        <span class="icon-calendar icon-large"></span>
                        New Admission
                    </a>

                    <div class="span12 tableContainer">
                        <table id="scheduled" class="well data-list">
                            <thead>
                            <tr>
                                <th>Date &amp; Time</th>
                                <th>Est. Stay</th>
                                <th>Admin. Type</th>
                                <th>Location</th>
                                <th>Provider</th>
                                <th>Diagnosis</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="availItem" ng-repeat="adm in adms | filter: sch">

                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.date}} {{adm.time}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.length}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.admType}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.serviceLocation}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.md}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.diagnosis}}</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </fieldset>

                <fieldset class="row-fluid">
                    <legend>Admitted</legend>

                    <p class="formInstructions span12">
                        To edit an admission, just click on an admission below.
                    </p>

                    <div class="span12 tableContainer">
                        <table id="checkedIn" class="well data-list">
                            <thead>
                            <tr>
                                <th>Date &amp; Time</th>
                                <th>Est. Stay</th>
                                <th>Admin. Type</th>
                                <th>Location</th>
                                <th>Provider</th>
                                <th>Diagnosis</th>
                            </tr>
                            </thead>
                            <tbody class="availListItems">
                            <tr class="availItem" ng-repeat="adm in adms | filter:admt">

                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.date}} {{adm.time}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.length}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.admType}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.serviceLocation}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.md}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.diagnosis}}</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </fieldset>

                <fieldset class="row-fluid">
                    <legend>Discharged</legend>

                    <p class="formInstructions span12">
                        To edit an admission, just click on an admission below.
                    </p>

                    <div class="span12 tableContainer">
                        <table id="checkedOut" class="well data-list">
                            <thead>
                            <tr>
                                <th>Date &amp; Time</th>
                                <th>Est. Stay</th>
                                <th>Admin. Type</th>
                                <th>Location</th>
                                <th>Provider</th>
                                <th>Diagnosis</th>
                            </tr>
                            </thead>
                            <tbody class="availListItems">
                            <tr class="availItem" ng-repeat="adm in adms | filter:dc">

                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.date}} {{adm.time}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.length}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.admType}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.serviceLocation}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.md}}</a>
                                </td>
                                <td>
                                    <a href="<?= $this->urlEdit; ?>"
                                        >{{adm.diagnosis}}</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </fieldset>
            </form>

        </section><!-- .tabContainer -->
    </div> <!-- .content: it was opened in ActHeader.php -->
</section> <!-- #mainPanel -->

<div id="signSubmitModal" class="modal hidden fade">

    <?php echo $this->partial('/partials/global/modal_submission.html'); ?>

    <div class="modal-footer">

        <a class="btn btn-cancel" data-dismiss="modal">Cancel</a>
        <a id="patientSignSubmit" ng-click="submit('adm', 'admForm', 'submitForm')" class="btn btn-success">Submit</a>
    </div>
</div>
</div><!-- end of #sectionContent -->