<?php
    // Construct new Pt Service Object
    $ptService = new Service_Pt();
    // Construct new Apt Service Object
    $aptService = new Service_Apt();
    // Construct new Outpatient Superbill Object
    $opSbService = new Service_OpSb();
?>

<script type="text/javascript">

    // Load the data into the PAS.data object
    DATA.reg = <?php echo $ptService->getJson($this->patientId); ?>;
    DATA.apt = <?php echo $aptService->getJson($this->aptId); ?>;
    DATA.newApt = {

        "ptInfo": {

            "uniqueId": <?= $this->patientId;?>,
            "newPt": null,
            "currentIns": null,
            "aptNum": null,
            "condRelatedTo": null
        },

        "md": {

            "clinic": null,
            "referring": null,
            "referringId": null
        },

        "aptDetails": {

            "serviceLocation": null,
            "startDate": null,
            "startTime": null,
            "length": null,
            "aptType": null,
            "reason": null,
            "aptId": null
        },

        "status": {

            "ptStatus": "Scheduled",
            "checkInDate": null,
            "checkInTime": null,
            "checkOutDate": null,
            "checkOutTime": null,
            "statusNotes": null
        },

        "notes": {

            "authorization": null,
            "reminderNotes": null,
            "equipment": null,
            "facility": null,
            "staff": null
        }
    };

    // Superbill stuff
    DATA.opSb = <?= $opSbService->getJson( $this->opSbId ); ?>;
    DATA.newOpSb = {

        "opSbDetails": {

            "opSbId": null,
            "aptId": null, // Links superbill to appointment
            "memo": null,
            "refNum": null,
            "authNotes": null,
            "medNotes": null,
            "busNotes": null
        },

        "diagCodes": [

            {"num": null, "name": null, "description": null}
        ],

        "procCodes": [

            {"num": null, "name": null, "modifier": null, "charge": null, "qty": null}
        ]
    };
    DATA.opSbList = <?= $opSbService->getByPtId( $this->patientId ); ?>;
    DATA.query = '<?= $this->searchTerms; ?>';
    DATA.searchTerms = '<?= $this->searchTerms; ?>';
</script>

<!-- AngularJS services for patient file -->
<script type="text/javascript" src="/js/services/serv-patient.js"></script>

<!-- AngularJS controllers for patient file -->
<script type="text/javascript" src="/js/controllers/ctrlr-patient.js"></script>

<!-- AngularJS controllers for patient file -->
<script type="text/javascript" src="/js/controllers/ctrlr-scheduler.js"></script>

<!-- AngularJS controllers for patient file -->
<script type="text/javascript" src="/js/controllers/ctrlr-exported-superbill.js"></script>

<div id="sectionContent" class="row-fluid tabContainer" role="main" ng-controller="PAS.ctrlr.patient">

<?= $this->ptsActionsNav(); ?>

<!-- Imports from views > helpers PtsSidebar.php -->
<!-- This handles what sidebar to use -->
<?= $this->ptsSidebar(); ?>

    <section id="mainPanel" class="<?= $this->mainPanelWidth; ?> parent">

    <!-- This imports the header, patient file navigation and the alert elements -->
    <?= $this->ptsHeader(); ?>

    <section class="tabContainer">

        <?php if (strcasecmp($this->data, 'superbill') == 0 || strcasecmp($this->data, 'appointment') == 0) { ?>

            <form name="opSbForm">

                <div ng-show="opSbForm.$invalid" class="alert">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Required fields:</strong> You have required fields that are still empty.
                </div>

                <?php echo $this->partial('/partials/global/op-superbill.html'); ?>

                <div class="form-actions <?= $this->mainPanelWidth; ?>">

                    <button class="btn btn-large btn-preview" data-toggle="modal" href="#exportedSuperbillModal">
                        <span class="icon-eye icon-large"></span> <i>Preview</i>
                    </button>

                    <button class="btn btn-large btn-cancel" data-toggle="modal" href="#confirmLossModal">
                        <span class="icon-x icon-large"></span> <i>Cancel</i>
                    </button>
                    <button ng-click="save('opSb', 'opSbForm')" ng-disabled="" data-toggle="modal"
                            href="#saveStatusModal" class="btn btn-success btn-large">
                        <span class="icon-install icon-large"></span> <i>Save</i>
                    </button>
                    <button class="btn btn-large btn-inverse" data-toggle="modal" href="#signSubmitModal"
                            ng-disabled="">
                        <span class="icon-drawer icon-large"></span> <i>Submit</i>
                    </button>
                </div>
            </form>

            <?php echo $this->partial('/patients/templates/modal_diag_search.html'); ?>
            <?php echo $this->partial('/patients/templates/modal_proc_search.html'); ?>
            <?php echo $this->partial('/patients/templates/modal_mod_search.html'); ?>

            <div id="signSubmitModal" class="modal hidden fade">

                <?php echo $this->partial('/partials/global/modal_submission.html'); ?>

                <div class="modal-footer">

                    <a class="btn btn-cancel" data-dismiss="modal">Cancel</a>
                    <a ng-click="submit('opSb', 'opSbForm', 'submitForm')" class="btn btn-success">Submit</a>
                </div>
            </div>

        <?php } else { ?>

            <form>

                <fieldset class="row-fluid">

                    <legend>Outpatient Superbills</legend>

                    <p class="formInstructions span9">
                        To view and/or edit a superbill, just click on it below.
                    </p><!-- Remove whitespace

                 --><a href="<?= $this->urlSbNew; ?>" class="newButton span3 no-padding">
                    <span class="icon-calendar icon-large"></span>
                        New Superbill
                    </a>

                    <div class="span12 tableContainer">
                        <table id="scheduled" class="well data-list">
                            <thead>
                                <tr>
                                    <th>Date &amp; Time</th>
                                    <th>Length</th>
                                    <th>Location</th>
                                    <th>Provider</th>
                                    <th>Apt. Type</th>
                                    <th>Diag Codes</th>
                                    <th>Proc Codes</th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr ng-repeat="opSb in sbs">

                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.date}} {{opSb.time}}</a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.length}}</a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.serviceLocation}}</a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.md}}</a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.aptType}}</a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.diagCount}}</a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->urlSbEdit; ?>">{{opSb.procCount}}</a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </fieldset>
            </form>

        <?php } ?>

        </section><!-- .tabContainer -->
    </div> <!-- .content: it was opened in ActHeader.php -->
</section> <!-- #mainPanel -->

<?php echo $this->partial('/partials/global/modal_apt_search.html'); ?>

<ng-include src="'/templates/includes/scheduler.html'" ng-controller="PAS.ctrlr.scheduler"></ng-include>

<div id="exportedSuperbillModal" class="modal modal-large hide fade">

    <div class="modal-header">
        <a data-dismiss="modal" class="close">&#x2612;</a>
        <h2>Generated Superbill: {{pt.firstName}} {{pt.lastName}} for {{aptDetails.startDate}}</h2>
    </div>

    <form name="exportedOpSuperBill" class="row-fluid modal-body">

        <ng-include src="'/templates/includes/export-op-superbill.html'"
        ng-controller="PAS.ctrlr.exportedSuperbill"></ng-include>
    </form>
</div>

</div><!-- end of #sectionContent -->