DROP TABLE IF EXISTS `adm`;
CREATE TABLE IF NOT EXISTS `adm` (
  `admDetailsAdmId` int(10) unsigned NULL,
  `ptInfoUniqueId` int(10) unsigned NULL,
  `ptInfoConfidential` varchar(255) NULL,
  `ptInfoCurrentIns` varchar(255) NULL,
  `ptInfoDiagnosis` varchar(255) NULL,
  `ptInfoAdmNum` varchar(255) NULL,
  `admDetailsAdmType` varchar(255) NULL,
  `admDetailsDate` varchar(255) NULL,
  `admDetailsTime` varchar(255) NULL,
  `admDetailsLength` varchar(255) NULL,
  `mdAdmitting` varchar(255) NULL,
  `mdAttending` varchar(255) NULL,
  `mdSurgical` varchar(255) NULL,
  `mdPrimary` varchar(255) NULL,
  `locationSpecialty` varchar(255) NULL,
  `locationWard` varchar(255) NULL,
  `locationRoomNumber` varchar(255) NULL,
  `locationBedNumber` varchar(255) NULL,
  `statusPtStatus` varchar(255) NULL,
  `statusAdmDate` varchar(255) NULL,
  `statusAdmTime` varchar(255) NULL,
  `statusDcDate` varchar(255) NULL,
  `statusDcTime` varchar(255) NULL,
  `statusDcNotes` varchar(255) NULL,
  `notesAuthorization` varchar(255) NULL,
  `notesReminderNotes` varchar(255) NULL,
  `notesEquipment` varchar(255) NULL,
  `notesFacility` varchar(255) NULL,
  `notesStaff` varchar(255) NULL,
  `createdBy` int(10) unsigned NULL,
  `createdDate` datetime NULL,
  `modifiedBy` int(10) unsigned NULL,
  `modifiedDate` datetime NULL,
  PRIMARY KEY (`admDetailsAdmId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `adm_working`;
CREATE TABLE IF NOT EXISTS `adm_working` (
  `admWorkingId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `admDetailsAdmId` int(10) unsigned NULL,
  `ptInfoUniqueId` int(10) unsigned NULL,
  `ptInfoConfidential` varchar(255) NULL,
  `ptInfoCurrentIns` varchar(255) NULL,
  `ptInfoDiagnosis` varchar(255) NULL,
  `ptInfoAdmNum` varchar(255) NULL,
  `admDetailsAdmType` varchar(255) NULL,
  `admDetailsDate` varchar(255) NULL,
  `admDetailsTime` varchar(255) NULL,
  `admDetailsLength` varchar(255) NULL,
  `mdAdmitting` varchar(255) NULL,
  `mdAttending` varchar(255) NULL,
  `mdSurgical` varchar(255) NULL,
  `mdPrimary` varchar(255) NULL,
  `locationSpecialty` varchar(255) NULL,
  `locationWard` varchar(255) NULL,
  `locationRoomNumber` varchar(255) NULL,
  `locationBedNumber` varchar(255) NULL,
  `statusPtStatus` varchar(255) NULL,
  `statusAdmDate` varchar(255) NULL,
  `statusAdmTime` varchar(255) NULL,
  `statusDcDate` varchar(255) NULL,
  `statusDcTime` varchar(255) NULL,
  `statusDcNotes` varchar(255) NULL,
  `notesAuthorization` varchar(255) NULL,
  `notesReminderNotes` varchar(255) NULL,
  `notesEquipment` varchar(255) NULL,
  `notesFacility` varchar(255) NULL,
  `notesStaff` varchar(255) NULL,
  `createdBy` int(10) unsigned NULL,
  `createdDate` datetime NULL,
  `modifiedBy` int(10) unsigned NULL,
  `modifiedDate` datetime NULL,
  PRIMARY KEY (`admWorkingId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `adm_submission`;
CREATE TABLE IF NOT EXISTS `adm_submission` (
  `submissionId` int(10) unsigned NULL,
  `admDetailsAdmId` int(10) unsigned NULL,
  `ptInfoUniqueId` int(10) unsigned NULL,
  `ptInfoConfidential` varchar(255) NULL,
  `ptInfoCurrentIns` varchar(255) NULL,
  `ptInfoDiagnosis` varchar(255) NULL,
  `ptInfoAdmNum` varchar(255) NULL,
  `admDetailsAdmType` varchar(255) NULL,
  `admDetailsDate` varchar(255) NULL,
  `admDetailsTime` varchar(255) NULL,
  `admDetailsLength` varchar(255) NULL,
  `mdAdmitting` varchar(255) NULL,
  `mdAttending` varchar(255) NULL,
  `mdSurgical` varchar(255) NULL,
  `mdPrimary` varchar(255) NULL,
  `locationSpecialty` varchar(255) NULL,
  `locationWard` varchar(255) NULL,
  `locationRoomNumber` varchar(255) NULL,
  `locationBedNumber` varchar(255) NULL,
  `statusPtStatus` varchar(255) NULL,
  `statusAdmDate` varchar(255) NULL,
  `statusAdmTime` varchar(255) NULL,
  `statusDcDate` varchar(255) NULL,
  `statusDcTime` varchar(255) NULL,
  `statusDcNotes` varchar(255) NULL,
  `notesAuthorization` varchar(255) NULL,
  `notesReminderNotes` varchar(255) NULL,
  `notesEquipment` varchar(255) NULL,
  `notesFacility` varchar(255) NULL,
  `notesStaff` varchar(255) NULL,
  `createdBy` int(10) unsigned NULL,
  `createdDate` datetime NULL,
  `modifiedBy` int(10) unsigned NULL,
  `modifiedDate` datetime NULL,
  PRIMARY KEY (`submissionId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;