DROP TABLE IF EXISTS `apt`;
CREATE TABLE IF NOT EXISTS `apt` (
  `aptDetailsAptId` int(10) unsigned NULL,
  `ptInfoUniqueId` int(10) unsigned NULL,
  `ptInfoNewPt` varchar(255) NULL,
  `ptInfoCurrentIns` varchar(255) NULL,
  `ptInfoAptNum` varchar(255) NULL,
  `clinicServiceLocation` varchar(255) NULL,
  `clinicMd` varchar(255) NULL,
  `aptDetailsStartDate` varchar(255) NULL,
  `aptDetailsStartTime` varchar(255) NULL,
  `aptDetailsLength` varchar(255) NULL,
  `aptDetailsAptType` varchar(255) NULL,
  `aptDetailsReason` varchar(255) NULL,
  `statusPtStatus` varchar(255) NULL,
  `statusCheckInDate` varchar(255) NULL,
  `statusCheckInTime` varchar(255) NULL,
  `statusCheckOutDate` varchar(255) NULL,
  `statusCheckOutTime` varchar(255) NULL,
  `statusStatusNotes` varchar(255) NULL,
  `notesAuthorization` varchar(255) NULL,
  `notesReminderNotes` varchar(255) NULL,
  `notesEquipment` varchar(255) NULL,
  `notesFacility` varchar(255) NULL,
  `notesStaff` varchar(255) NULL,
  `createdBy` int(10) unsigned NULL,
  `createdDate` datetime NULL,
  `modifiedBy` int(10) unsigned NULL,
  `modifiedDate` datetime NULL,
  PRIMARY KEY (`aptDetailsAptId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `apt_working`;
CREATE TABLE IF NOT EXISTS `apt_working` (
  `aptWorkingId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `aptDetailsAptId` int(10) unsigned NULL,
  `ptInfoUniqueId` int(10) unsigned NULL,
  `ptInfoNewPt` varchar(255) NULL,
  `ptInfoCurrentIns` varchar(255) NULL,
  `ptInfoAptNum` varchar(255) NULL,
  `clinicServiceLocation` varchar(255) NULL,
  `clinicMd` varchar(255) NULL,
  `aptDetailsStartDate` varchar(255) NULL,
  `aptDetailsStartTime` varchar(255) NULL,
  `aptDetailsLength` varchar(255) NULL,
  `aptDetailsAptType` varchar(255) NULL,
  `aptDetailsReason` varchar(255) NULL,
  `statusPtStatus` varchar(255) NULL,
  `statusCheckInDate` varchar(255) NULL,
  `statusCheckInTime` varchar(255) NULL,
  `statusCheckOutDate` varchar(255) NULL,
  `statusCheckOutTime` varchar(255) NULL,
  `statusStatusNotes` varchar(255) NULL,
  `notesAuthorization` varchar(255) NULL,
  `notesReminderNotes` varchar(255) NULL,
  `notesEquipment` varchar(255) NULL,
  `notesFacility` varchar(255) NULL,
  `notesStaff` varchar(255) NULL,
  `createdBy` int(10) unsigned NULL,
  `createdDate` datetime NULL,
  `modifiedBy` int(10) unsigned NULL,
  `modifiedDate` datetime NULL,
  PRIMARY KEY (`aptWorkingId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `apt_submission`;
CREATE TABLE IF NOT EXISTS `apt_submission` (
  `submissionId` int(10) unsigned NULL,
  `aptDetailsAptId` int(10) unsigned NULL,
  `ptInfoUniqueId` int(10) unsigned NULL,
  `ptInfoNewPt` varchar(255) NULL,
  `ptInfoCurrentIns` varchar(255) NULL,
  `ptInfoAptNum` varchar(255) NULL,
  `clinicServiceLocation` varchar(255) NULL,
  `clinicMd` varchar(255) NULL,
  `aptDetailsStartDate` varchar(255) NULL,
  `aptDetailsStartTime` varchar(255) NULL,
  `aptDetailsLength` varchar(255) NULL,
  `aptDetailsAptType` varchar(255) NULL,
  `aptDetailsReason` varchar(255) NULL,
  `statusPtStatus` varchar(255) NULL,
  `statusCheckInDate` varchar(255) NULL,
  `statusCheckInTime` varchar(255) NULL,
  `statusCheckOutDate` varchar(255) NULL,
  `statusCheckOutTime` varchar(255) NULL,
  `statusStatusNotes` varchar(255) NULL,
  `notesAuthorization` varchar(255) NULL,
  `notesReminderNotes` varchar(255) NULL,
  `notesEquipment` varchar(255) NULL,
  `notesFacility` varchar(255) NULL,
  `notesStaff` varchar(255) NULL,
  `createdBy` int(10) unsigned NULL,
  `createdDate` datetime NULL,
  `modifiedBy` int(10) unsigned NULL,
  `modifiedDate` datetime NULL,
  PRIMARY KEY (`submissionId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;