DROP TABLE IF EXISTS `pas`.`modifier`;
CREATE TABLE  `pas`.`modifier` (
`code` VARCHAR( 50 ) NOT NULL ,
`description` VARCHAR( 1000 ) NOT NULL ,
PRIMARY KEY (  `code` )
) ENGINE = MYISAM ;
insert into modifier(`code`, `description`) values('22', 'Increased Procedural Services');
insert into modifier(`code`, `description`) values('23', 'Unusual Anesthesia');
insert into modifier(`code`, `description`) values('24', 'Unrelated E&M Same Physician PostOp');
insert into modifier(`code`, `description`) values('25', 'Significant, Separately Identifiable E&M Same Phy & Day');
insert into modifier(`code`, `description`) values('26', 'Professional Component');
insert into modifier(`code`, `description`) values('27', 'Multiple Outpatient Hospital E/M Same Date');
insert into modifier(`code`, `description`) values('32', 'Mandated Services');
insert into modifier(`code`, `description`) values('33', 'Preventive Services');
insert into modifier(`code`, `description`) values('47', 'Anesthesia by Surgeon');
insert into modifier(`code`, `description`) values('50', 'Bilateral Procedure');
insert into modifier(`code`, `description`) values('51', 'Multiple Procedures');
insert into modifier(`code`, `description`) values('52', 'Reduced Services');
insert into modifier(`code`, `description`) values('53', 'Discontinued Procedure');
insert into modifier(`code`, `description`) values('54', 'Surgical Care Only');
insert into modifier(`code`, `description`) values('55', 'Postoperative Management Only');
insert into modifier(`code`, `description`) values('56', 'Preoperative Management Only');
insert into modifier(`code`, `description`) values('57', 'Decision for Surgery');
insert into modifier(`code`, `description`) values('58', 'Staged/Related Proc/Srvc Same Phy PostOp');
insert into modifier(`code`, `description`) values('59', 'Distinct Procedural Service');
insert into modifier(`code`, `description`) values('62', 'Two Surgeons');
insert into modifier(`code`, `description`) values('63', 'Procedure Performed on Infants less than 4 kg');
insert into modifier(`code`, `description`) values('66', 'Surgical Team');
insert into modifier(`code`, `description`) values('73', 'Discont. OutPat Hosp/ACS Prior to Anesthesia');
insert into modifier(`code`, `description`) values('74', 'Discont. OutPat Hosp/ACS After Anesthesia');
insert into modifier(`code`, `description`) values('76', 'Repeat Procedure or Service by Same Physician');
insert into modifier(`code`, `description`) values('77', 'Repeat Procedure by Another Physician');
insert into modifier(`code`, `description`) values('78', 'Unplanned Return to OR Same Phy PostOp');
insert into modifier(`code`, `description`) values('79', 'Unrelated Proc by Same Phy PostOp');
insert into modifier(`code`, `description`) values('80', 'Assistant Surgeon');
insert into modifier(`code`, `description`) values('81', 'Minimum Assistant Surgeon');
insert into modifier(`code`, `description`) values('82', 'Assistant Surgeon (when qual resident surgeon NA)');
insert into modifier(`code`, `description`) values('90', 'Reference (Outside) Laboratory');
insert into modifier(`code`, `description`) values('91', 'Repeat Clinical Diagnostic Laboratory Test');
insert into modifier(`code`, `description`) values('92', 'Alternative Laboratory Platform Testing');
insert into modifier(`code`, `description`) values('99', 'Multiple Modifiers');
insert into modifier(`code`, `description`) values('0A-0Z', 'Neoplasia (Solid Tumor, Excluding Sarcoma and Lymphoma)');
insert into modifier(`code`, `description`) values('1A-1Z', 'Neoplasia (Sarcoma)');
insert into modifier(`code`, `description`) values('2A-2Z', 'Neoplasia (Lymphoid/Hematopoietic)');
insert into modifier(`code`, `description`) values('3A-3Z', 'Non-Neoplastic Hematology/Coagulation');
insert into modifier(`code`, `description`) values('4A-4Z', 'Histocompatibility/Blood Typing/Identity/Microsatellite');
insert into modifier(`code`, `description`) values('5A-5Z', 'Neurologic, Non-Neoplastic');
insert into modifier(`code`, `description`) values('6A-6Z', 'Muscular, Non-Neoplastic');
insert into modifier(`code`, `description`) values('7A-7Z', 'Metabolic, Other');
insert into modifier(`code`, `description`) values('8A-8Z', 'Metabolic, Transport');
insert into modifier(`code`, `description`) values('9A-9L', 'Metabolic-Pharmacogenetics');
insert into modifier(`code`, `description`) values('9M-Z', 'Dysmorphology');
insert into modifier(`code`, `description`) values('A1', 'Dressing for one wound');
insert into modifier(`code`, `description`) values('A2', 'Dressing for two wounds');
insert into modifier(`code`, `description`) values('A3', 'Dressing for three wounds');
insert into modifier(`code`, `description`) values('A4', 'Dressing for four wounds');
insert into modifier(`code`, `description`) values('A5', 'Dressing for five wounds');
insert into modifier(`code`, `description`) values('A6', 'Dressing for six wounds');
insert into modifier(`code`, `description`) values('A7', 'Dressing for seven wounds');
insert into modifier(`code`, `description`) values('A8', 'Dressing for eight wounds');
insert into modifier(`code`, `description`) values('A9', 'Dressing for nine or more wounds');
insert into modifier(`code`, `description`) values('AA', 'Anesthesia services performed personally by anesthesiologist');
insert into modifier(`code`, `description`) values('AD', 'Medical supervision by a physician: more than four concurrent anesthesia procedures');
insert into modifier(`code`, `description`) values('AH', 'Clinical psychologist');
insert into modifier(`code`, `description`) values('AJ', 'Clinical social worker');
insert into modifier(`code`, `description`) values('AI', 'Principal physician of record');
insert into modifier(`code`, `description`) values('AM', 'Physician Assistant (PA) services');
insert into modifier(`code`, `description`) values('AP', 'Determination of refractive state was not performed in the course of diagnostic ophthalmologic examination');
insert into modifier(`code`, `description`) values('AS', 'Physician assistant, nurse practitioner, or clinical nurse specialist services for assistant at surgery');
insert into modifier(`code`, `description`) values('AT', 'Acute treatment (this modifier should be used when reporting services 98940, 98941, 98942)');
insert into modifier(`code`, `description`) values('AU', 'Item furnished in conjunction with a urological, ostomy, or tracheostomy supply');
insert into modifier(`code`, `description`) values('AV', 'Item furnished in conjunction with a prosthetic device, prosthetic or orthotic');
insert into modifier(`code`, `description`) values('AW', 'Item furnished in conjunction with a surgical dressing');
insert into modifier(`code`, `description`) values('AX', 'Item furnished in conjunction with dialysis services');
insert into modifier(`code`, `description`) values('BA', 'Item furnished in conjunction with parenteral enteral nutrition (PEN) services');
insert into modifier(`code`, `description`) values('BO', 'Orally administered nutrition, not by feeding tube');
insert into modifier(`code`, `description`) values('BP', 'The beneficiary has been informed of the purchase and rental options and has elected to purchase the item');
insert into modifier(`code`, `description`) values('BR', 'The beneficiary has been informed of the purchase and rental options and has elected to rent the item');
insert into modifier(`code`, `description`) values('BU', 'The beneficiary has been informed of the purchase and rental options and after 30 days has not informed the supplier of his/her decision');
insert into modifier(`code`, `description`) values('CC', 'Procedure code change (use CC when procedure code submitted was changed either for administrative reasons or because an incorrect code was filed)');
insert into modifier(`code`, `description`) values('E1', 'Upper left, eyelid');
insert into modifier(`code`, `description`) values('E2', 'Lower left, eyelid');
insert into modifier(`code`, `description`) values('E3', 'Upper right, eyelid');
insert into modifier(`code`, `description`) values('E4', 'Lower right, eyelid');
insert into modifier(`code`, `description`) values('EJ', 'Subsequent claims for a defined course of therapy (e.g., EPO, sodium hyaluronate, infliximab)');
insert into modifier(`code`, `description`) values('EM', 'Emergency reserve supply (for ESRD benefit only)');
insert into modifier(`code`, `description`) values('EP', 'Service provided as part of Medicaid early periodic screening diagnosis and treatment (EPSDT) program');
insert into modifier(`code`, `description`) values('ET', 'Emergency treatment (dental procedures performed in emergency situations should show the modifier "ET")');
insert into modifier(`code`, `description`) values('EY', 'No physician or other licensed health care provider order for this item or service');
insert into modifier(`code`, `description`) values('F1', 'Left hand, second digit');
insert into modifier(`code`, `description`) values('F2', 'Left hand, third digit');
insert into modifier(`code`, `description`) values('F3', 'Left hand, fourth digit');
insert into modifier(`code`, `description`) values('F4', 'Left hand, fifth digit');
insert into modifier(`code`, `description`) values('F5', 'Right hand, thumb');
insert into modifier(`code`, `description`) values('F6', 'Right hand, second digit');
insert into modifier(`code`, `description`) values('F7', 'Right hand, third digit');
insert into modifier(`code`, `description`) values('F8', 'Right hand, fourth digit');
insert into modifier(`code`, `description`) values('F9', 'Right hand, fifth digit');
insert into modifier(`code`, `description`) values('FA', 'Left hand, thumb');
insert into modifier(`code`, `description`) values('FP', 'Service provided as part of Medicaid family planning program');
insert into modifier(`code`, `description`) values('G1', 'Most recent urea reduction ration (URR) reading of less than 60');
insert into modifier(`code`, `description`) values('G2', 'Most recent urea reduction ration (URR) reading of 60 to 64.9');
insert into modifier(`code`, `description`) values('G3', 'Most recent urea reduction ration (URR) reading of 65 to 69.9');
insert into modifier(`code`, `description`) values('G4', 'Most recent urea reduction ration (URR) reading of 70 to 74.9');
insert into modifier(`code`, `description`) values('G5', 'Most recent urea reduction ration (URR) reading of 75 or greater');
insert into modifier(`code`, `description`) values('G6', 'ESRD patient for whom less than six dialysis sessions have been provided in a month');
insert into modifier(`code`, `description`) values('G7', 'Pregnancy resulted from rape or incest or pregnancy certified by physician as life-threatening');
insert into modifier(`code`, `description`) values('G8', 'Monitored anesthesia care (MAC) for deep complex, complicated, or markedly invasive surgical procedure');
insert into modifier(`code`, `description`) values('G9', 'Monitored anesthesia care for patient who has history of severe cardio-pulmonary condition');
insert into modifier(`code`, `description`) values('GA', 'Waiver of liability statement on file');
insert into modifier(`code`, `description`) values('GB', 'Claim being re-submitted for payment because it is no longer covered under a global payment demonstration');
insert into modifier(`code`, `description`) values('GC', 'This service has been performed in part by a resident under the direction of a teaching physician');
insert into modifier(`code`, `description`) values('GE', 'This service has been performed by a resident without the presence of teaching physician under the primary care exception');
insert into modifier(`code`, `description`) values('GG', 'Performance and payment of a screening mammogram and diagnostic mammogram on the same patient, same day');
insert into modifier(`code`, `description`) values('GH', 'Diagnostic mammogram converted from screening mammogram on same day');
insert into modifier(`code`, `description`) values('GJ', 'Physician or practitioner emergency or urgent service');
insert into modifier(`code`, `description`) values('GK', 'Actual item/service ordered by a physician, item associated with GA or GZ modifier');
insert into modifier(`code`, `description`) values('GL', 'Medically unnecessary upgrade provided instead of standard item, no charge, no advance beneficiary notice (ABN)');
insert into modifier(`code`, `description`) values('GM', 'Multiple patients on one ambulance trip');
insert into modifier(`code`, `description`) values('GN', 'Service delivered personally by a speech-language pathologist or under an outpatient speech-language pathology plan of care');
insert into modifier(`code`, `description`) values('GO', 'Service delivered personally by an occupational therapist or under an outpatient occupational therapy plan of care');
insert into modifier(`code`, `description`) values('GP', 'Service delivered personally by a physical therapist or under an outpatient physical therapy plan of care');
insert into modifier(`code`, `description`) values('GQ', 'Via asynchronous telecommunications system');
insert into modifier(`code`, `description`) values('GT', 'Via interactive audio and video telecommunication systems');
insert into modifier(`code`, `description`) values('GV', 'Attending physician not employer-paid under arrangement by the patient\'s hospice provider');
insert into modifier(`code`, `description`) values('GW', 'Service not related to the hospice patient\'s terminal condition');
insert into modifier(`code`, `description`) values('GY', 'Item or service statutorily excluded or does not meet the definition of any Medicare benefit');
insert into modifier(`code`, `description`) values('GZ', 'Item or service expected to be denied as not reasonable and necessary');
insert into modifier(`code`, `description`) values('H9', 'Court ordered');
insert into modifier(`code`, `description`) values('HA', 'Child/adolescent program');
insert into modifier(`code`, `description`) values('HB', 'Adult program, non-geriatric');
insert into modifier(`code`, `description`) values('HC', 'Adult program, geriatric');
insert into modifier(`code`, `description`) values('HD', 'Pregnant/parenting women\'s program');
insert into modifier(`code`, `description`) values('HE', 'Mental health program');
insert into modifier(`code`, `description`) values('HF', 'Substance abuse program');
insert into modifier(`code`, `description`) values('HG', 'Opioid addiction treatment program');
insert into modifier(`code`, `description`) values('HH', 'Integrated mental health/substance abuse program');
insert into modifier(`code`, `description`) values('HI', 'Integrated mental health and mental retardation/developmental disabilities program');
insert into modifier(`code`, `description`) values('HJ', 'Employee assistance program');
insert into modifier(`code`, `description`) values('HK', 'Specialized mental health programs for high-risk populations');
insert into modifier(`code`, `description`) values('HL', 'Intern');
insert into modifier(`code`, `description`) values('HM', 'Less than bachelor degree level');
insert into modifier(`code`, `description`) values('HN', 'Bachelors degree level');
insert into modifier(`code`, `description`) values('HO', 'Masters degree level');
insert into modifier(`code`, `description`) values('HP', 'Doctoral level');
insert into modifier(`code`, `description`) values('HQ', 'Group setting');
insert into modifier(`code`, `description`) values('HR', 'Family/couple with client present');
insert into modifier(`code`, `description`) values('HS', 'Family/couple without client present');
insert into modifier(`code`, `description`) values('HT', 'Multi-disciplinary team');
insert into modifier(`code`, `description`) values('HU', 'Funded by child welfare agency');
insert into modifier(`code`, `description`) values('HV', 'Funded by state addictions agency');
insert into modifier(`code`, `description`) values('HW', 'Funded by state mental health agency');
insert into modifier(`code`, `description`) values('HX', 'Funded by county/local agency');
insert into modifier(`code`, `description`) values('HY', 'Funded by juvenile justice agency');
insert into modifier(`code`, `description`) values('HZ', 'Funded by criminal justice agency');
insert into modifier(`code`, `description`) values('JW', 'Drug amount discarded/not administered to any patient');
insert into modifier(`code`, `description`) values('K0', 'Lower extremity prosthesis functional level 0 - does not have the ability or potential to ambulate or transfer safely with or without assistance and a prosthesis does not enhance their quality of life or mobility');
insert into modifier(`code`, `description`) values('K1', 'Lower extremity prosthesis functional level 1 - has the ability or potential to use prosthesis for transfers or ambulation on level surfaces at fixed cadence. Typical of the limited and unlimited household ambulator.');
insert into modifier(`code`, `description`) values('K2', 'Lower extremity prosthesis functional level 2 - has the ability or potential for ambulation with the ability to traverse low level environmental barriers such as curbs, stairs, or uneven surfaces. Typical of the limited community ambulator.');
insert into modifier(`code`, `description`) values('K3', 'Lower extremity prosthesis functional level 3 - has the ability or potential for ambulation with variable cadence. Typical of the community ambulator who has the ability to transverse most environmental barriers and may have vocational, therapeutic, or exercise activity that demands prosthetic utilization beyond simple locomotion.');
insert into modifier(`code`, `description`) values('K4', 'Lower extremity prosthesis function level 4 - has the ability or potential for prosthetic ambulation that exceeds the basic ambulation skills, exhibiting high impact, stress, or energy levels. Typical of the prosthetic demands of the child, active adult, or athlete.');
insert into modifier(`code`, `description`) values('KA', 'Add-on option/accessory for wheelchair');
insert into modifier(`code`, `description`) values('KB', 'Beneficiary-requested upgrade for ABN, more than four modifiers indicated on claim');
insert into modifier(`code`, `description`) values('KH', 'DMEPOS item, initial claim, purchase or first month rental');
insert into modifier(`code`, `description`) values('KI', 'DMEPOS item, second or third month rental');
insert into modifier(`code`, `description`) values('KJ', 'DMEPOS item, parenteral enteral nutrition (PEN) pump or capped rental, months four to fifteen');
insert into modifier(`code`, `description`) values('KM', 'Replacement of facial prosthesis including new impression/moulage');
insert into modifier(`code`, `description`) values('KN', 'Replacement of facial prosthesis using previous master model');
insert into modifier(`code`, `description`) values('KO', 'Single drug unit dose formulation');
insert into modifier(`code`, `description`) values('KP', 'First drug of a multiple drug unit dose formulation');
insert into modifier(`code`, `description`) values('KQ', 'Second or subsequent drug of a multiple drug unit dose formulation');
insert into modifier(`code`, `description`) values('KR', 'Rental item, billing for partial month');
insert into modifier(`code`, `description`) values('KS', 'Glucose monitor supply for diabetic beneficiary not treated with insulin');
insert into modifier(`code`, `description`) values('KX', 'Specific required documentation on file');
insert into modifier(`code`, `description`) values('LC', 'Left circumflex coronary artery');
insert into modifier(`code`, `description`) values('LD', 'Left anterior descending coronary artery');
insert into modifier(`code`, `description`) values('LL', 'Lease/rental (use "LL" modifier when DME equipment rental is to be applied against the purchase price)');
insert into modifier(`code`, `description`) values('LR', 'Laboratory round trip');
insert into modifier(`code`, `description`) values('LS', 'FDA-monitored intraocular lens implant');
insert into modifier(`code`, `description`) values('LT', 'Left side (used to identify procedures performed on the left side of the body)');
insert into modifier(`code`, `description`) values('MS', 'Six month maintenance and servicing fee for reasonable and necessary parts and labor which are not covered under any manufacturer or supplier warranty');
insert into modifier(`code`, `description`) values('NR', 'New when rented (use the "NR" modifier when DME that was new at the time of rental is subsequently purchased)');
insert into modifier(`code`, `description`) values('NU', 'New equipment (for DME equipment)');
insert into modifier(`code`, `description`) values('P1', 'A normal healthy patient');
insert into modifier(`code`, `description`) values('P2', 'A patient with mild systemic disease');
insert into modifier(`code`, `description`) values('P3', 'A patient with severe systemic disease');
insert into modifier(`code`, `description`) values('P4', 'A patient with severe systemic disease that is a constant threat to life');
insert into modifier(`code`, `description`) values('P5', 'A moribund patient who is not expected to survive without the operation');
insert into modifier(`code`, `description`) values('P6', 'A declared brain-dead patient whose organs are being removed for donor purposes');
insert into modifier(`code`, `description`) values('PL', 'Progressive addition lenses');
insert into modifier(`code`, `description`) values('Q2', 'CMS/ORD demonstration project procedure/service');
insert into modifier(`code`, `description`) values('Q3', 'Live kidney donor; Services associated with post-operative medical complications directly related to the donation');
insert into modifier(`code`, `description`) values('Q4', 'Service for ordering/referring physician qualifies as a service exemption');
insert into modifier(`code`, `description`) values('Q5', 'Service furnished by a substitute physician under a reciprocal billing arrangement');
insert into modifier(`code`, `description`) values('Q6', 'Service furnished by locum tenens physician');
insert into modifier(`code`, `description`) values('Q7', 'One class A finding');
insert into modifier(`code`, `description`) values('Q8', 'Two class B findings');
insert into modifier(`code`, `description`) values('Q9', 'One class B and two class C findings');
insert into modifier(`code`, `description`) values('QA', 'FDA investigational device exemption');
insert into modifier(`code`, `description`) values('QB', 'Physician providing service in a rural HPSA');
insert into modifier(`code`, `description`) values('QC', 'Single channel monitoring');
insert into modifier(`code`, `description`) values('QD', 'Recording and storage in solid state memory by a digital recorder');
insert into modifier(`code`, `description`) values('QE', 'Prescribed amount of oxygen is less than 1 liter per minute (LPM)');
insert into modifier(`code`, `description`) values('QF', 'Prescribed amount of oxygen exceeds 4 liters per minute (LPM) and portable oxygen is prescribed');
insert into modifier(`code`, `description`) values('QG', 'Prescribed amount of oxygen is greater than 4 liters per minute (LPM)');
insert into modifier(`code`, `description`) values('QH', 'Oxygen conserving device is being used with an oxygen delivery system');
insert into modifier(`code`, `description`) values('QJ', 'Services/items provided to a prisoner or patient in state or local custody however the state or local government, as applicable, meets the requirements in 42 CFR 411.4 (B)');
insert into modifier(`code`, `description`) values('QK', 'Medical direction of two, three, or four concurrent anesthesia procedures involving qualified individuals');
insert into modifier(`code`, `description`) values('QL', 'Patient pronounced dead after ambulance called');
insert into modifier(`code`, `description`) values('QM', 'Ambulance service provided under arrangement by a provider of services');
insert into modifier(`code`, `description`) values('QN', 'Ambulance service furnished directly by provider of services');
insert into modifier(`code`, `description`) values('QP', 'Documentation is on file showing that the laboratory test(s) as ordered individually or ordered as a CPT-recognized panel other than automated profile codes 80002-80019, G0058, G0059, and G0060');
insert into modifier(`code`, `description`) values('QQ', 'Claim submitted with a written statement of intent');
insert into modifier(`code`, `description`) values('QS', 'Monitored anesthesia care service');
insert into modifier(`code`, `description`) values('QT', 'Recording and storage on tape by an analog tape recorder');
insert into modifier(`code`, `description`) values('QU', 'Physician provider service in an urban HPSA');
insert into modifier(`code`, `description`) values('QV', 'Item or service provided as routine care in a Medicare-qualifying clinical trial');
insert into modifier(`code`, `description`) values('QW', 'CLIA-waived test');
insert into modifier(`code`, `description`) values('QX', 'Certified Registered Nurse Anesthetist (CRNA) service with medical direction by a physician');
insert into modifier(`code`, `description`) values('QY', 'Medical direction of one Certified Registered Nurse Anesthetist (CRNA) by an anesthesiologist');
insert into modifier(`code`, `description`) values('QZ', 'Certified Registered Nurse Anesthetist (CRNA) service without medical direction by a physician');
insert into modifier(`code`, `description`) values('RC', 'Right coronary artery');
insert into modifier(`code`, `description`) values('RP', 'Replacement and repair. "RP" may be used to indicate replacement of DME, orthotic, and prosthetic devices which have been in use for sometime. The claim shows the code for the part, followed by the "RP" modifier and the charge for the part.');
insert into modifier(`code`, `description`) values('RR', 'Rental (use "RR" modifier when DME is to be rented)');
insert into modifier(`code`, `description`) values('RT', 'Right side (used to identify procedures performed on the right side of the body)');
insert into modifier(`code`, `description`) values('SA', 'Nurse practitioner rendering service in collaboration with a physician');
insert into modifier(`code`, `description`) values('SB', 'Nurse midwife');
insert into modifier(`code`, `description`) values('SC', 'Medically necessary service or supply');
insert into modifier(`code`, `description`) values('SD', 'Services provided by registered nurse with specialized, highly technical home infusion');
insert into modifier(`code`, `description`) values('SE', 'State and/or federally-funded programs/services');
insert into modifier(`code`, `description`) values('SF', 'Second opinion ordered by professional review organization (PRO) per section 9401, pl. 99-272 (100% reimbursement¾no Medicare deductible or coinsurance)');
insert into modifier(`code`, `description`) values('SG', 'Ambulatory surgical center (ASC) facility service');
insert into modifier(`code`, `description`) values('SH', 'Second concurrently administered infusion therapy');
insert into modifier(`code`, `description`) values('SJ', 'Third or more concurrently administered infusion therapy');
insert into modifier(`code`, `description`) values('SK', 'Member of high risk population (use only with codes for immunization)');
insert into modifier(`code`, `description`) values('SL', 'State-supplied vaccine');
insert into modifier(`code`, `description`) values('SQ', 'Item ordered by home health');
insert into modifier(`code`, `description`) values('ST', 'Related to trauma or injury');
insert into modifier(`code`, `description`) values('SU', 'Procedure performed in physician\'s office (to denote use of facility equipment)');
insert into modifier(`code`, `description`) values('SV', 'Pharmaceuticals delivered to patient\'s home but not utilized');
insert into modifier(`code`, `description`) values('T1', 'Left foot, second digit');
insert into modifier(`code`, `description`) values('T2', 'Left foot, third digit');
insert into modifier(`code`, `description`) values('T3', 'Left foot, fourth digit');
insert into modifier(`code`, `description`) values('T4', 'Left foot, fifth digit');
insert into modifier(`code`, `description`) values('T5', 'Right foot, great toe');
insert into modifier(`code`, `description`) values('T6', 'Right foot, second digit');
insert into modifier(`code`, `description`) values('T7', 'Right foot, third digit');
insert into modifier(`code`, `description`) values('T8', 'Right foot, fourth digit');
insert into modifier(`code`, `description`) values('T9', 'Right foot, fifth digit');
insert into modifier(`code`, `description`) values('TA', 'Left foot, great toe');
insert into modifier(`code`, `description`) values('TC', 'Technical component');
insert into modifier(`code`, `description`) values('TD', 'RN');
insert into modifier(`code`, `description`) values('TE', 'LPN/LVN');
insert into modifier(`code`, `description`) values('TF', 'Intermediate level of care');
insert into modifier(`code`, `description`) values('TG', 'Complex/high tech level of care');
insert into modifier(`code`, `description`) values('TH', 'Obstetrical treatment/services, pre-natal or post-partum');
insert into modifier(`code`, `description`) values('TJ', 'Program group, child and/or adolescent');
insert into modifier(`code`, `description`) values('TK', 'Extra patient or passenger, non-ambulance (established for state Medicaid agencies)');
insert into modifier(`code`, `description`) values('TL', 'Early intervention/individualized family services plan (IFSP) (established for state Medicaid agencies)');
insert into modifier(`code`, `description`) values('TM', 'Individualized education program (IEP) (established for state Medicaid agencies)');
insert into modifier(`code`, `description`) values('TN', 'Rural/outside providers customary service area (established for state Medicaid agencies)');
insert into modifier(`code`, `description`) values('TP', 'Medical transport, unloaded vehicle (established for state Medicaid agencies)');
insert into modifier(`code`, `description`) values('TQ', 'Basic life support transport by a volunteer ambulance provider (established for state Medicaid agencies)');
insert into modifier(`code`, `description`) values('TR', 'School-based individualized education program (iep) services provided outside the public school district responsible for the student');
insert into modifier(`code`, `description`) values('TS', 'Follow-up service');
insert into modifier(`code`, `description`) values('TT', 'Individualized service provided to more than one patient in same setting');
insert into modifier(`code`, `description`) values('TU', 'Special payment rate, overtime');
insert into modifier(`code`, `description`) values('TV', 'Special payment rate, holidays/weekends');
insert into modifier(`code`, `description`) values('TW', 'Back-up equipment');
insert into modifier(`code`, `description`) values('U1', 'Medicaid level of care 1');
insert into modifier(`code`, `description`) values('U2', 'Medicaid level of care 2');
insert into modifier(`code`, `description`) values('U3', 'Medicaid level of care 3');
insert into modifier(`code`, `description`) values('U4', 'Medicaid level of care 4');
insert into modifier(`code`, `description`) values('U5', 'Medicaid level of care 5');
insert into modifier(`code`, `description`) values('U6', 'Medicaid level of care 6');
insert into modifier(`code`, `description`) values('U7', 'Medicaid level of care 7');
insert into modifier(`code`, `description`) values('U8', 'Medicaid level of care 8');
insert into modifier(`code`, `description`) values('U9', 'Medicaid level of care 9');
insert into modifier(`code`, `description`) values('UA', 'Medicaid level of care 10');
insert into modifier(`code`, `description`) values('UB', 'Medicaid level of care 11');
insert into modifier(`code`, `description`) values('UC', 'Medicaid level of care 12');
insert into modifier(`code`, `description`) values('UD', 'Medicaid level of care 13');
insert into modifier(`code`, `description`) values('UE', 'Used durable medical equipment');
insert into modifier(`code`, `description`) values('VP', 'Aphakic patient');

