DROP TABLE IF EXISTS `adm`;
CREATE TABLE `adm`  ( 
	`admDetailsAdmId`   	int(10) UNSIGNED NOT NULL,
	`ptInfoUniqueId`    	int(10) UNSIGNED NOT NULL,
	`ptInfoConfidential`	varchar(255) NOT NULL,
	`ptInfoCurrentIns`  	varchar(255) NOT NULL,
	`ptInfoDiagnosis`   	varchar(255) NOT NULL,
	`ptInfoAdmNum`      	varchar(255) NOT NULL,
	`admDetailsAdmType` 	varchar(255) NOT NULL,
	`admDetailsDate`    	varchar(255) NOT NULL,
	`admDetailsTime`    	varchar(255) NOT NULL,
	`admDetailsLength`  	varchar(255) NOT NULL,
	`mdAdmitting`       	varchar(255) NOT NULL,
	`mdAttending`       	varchar(255) NOT NULL,
	`mdSurgical`        	varchar(255) NOT NULL,
	`mdPrimary`         	varchar(255) NOT NULL,
	`locationSpecialty` 	varchar(255) NOT NULL,
	`locationWard`      	varchar(255) NOT NULL,
	`locationRoomNumber`	varchar(255) NOT NULL,
	`locationBedNumber` 	varchar(255) NOT NULL,
	`statusPtStatus`    	varchar(255) NOT NULL,
	`statusAdmDate`     	varchar(255) NOT NULL,
	`statusAdmTime`     	varchar(255) NOT NULL,
	`statusDcDate`      	varchar(255) NOT NULL,
	`statusDcTime`      	varchar(255) NOT NULL,
	`statusDcNotes`     	varchar(255) NOT NULL,
	`notesAuthorization`	varchar(255) NOT NULL,
	`notesReminderNotes`	varchar(255) NOT NULL,
	`notesEquipment`    	varchar(255) NOT NULL,
	`notesFacility`     	varchar(255) NOT NULL,
	`notesStaff`        	varchar(255) NOT NULL,
	`createdBy`            	int(10) UNSIGNED NOT NULL,
	`createdDate`          	datetime NOT NULL,
	`modifiedBy`           	int(10) UNSIGNED NOT NULL,
	`modifiedDate`         	datetime NOT NULL,
	PRIMARY KEY(`admDetailsAdmId`)
);
DROP TABLE IF EXISTS `adm_working`;
CREATE TABLE `adm_working`  ( 
    `admWorkingId`          int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
	`admDetailsAdmId`   	int(10) UNSIGNED NOT NULL,
	`ptInfoUniqueId`    	int(10) UNSIGNED NOT NULL,
	`ptInfoConfidential`	varchar(255) NOT NULL,
	`ptInfoCurrentIns`  	varchar(255) NOT NULL,
	`ptInfoDiagnosis`   	varchar(255) NOT NULL,
	`ptInfoAdmNum`      	varchar(255) NOT NULL,
	`admDetailsAdmType` 	varchar(255) NOT NULL,
	`admDetailsDate`    	varchar(255) NOT NULL,
	`admDetailsTime`    	varchar(255) NOT NULL,
	`admDetailsLength`  	varchar(255) NOT NULL,
	`mdAdmitting`       	varchar(255) NOT NULL,
	`mdAttending`       	varchar(255) NOT NULL,
	`mdSurgical`        	varchar(255) NOT NULL,
	`mdPrimary`         	varchar(255) NOT NULL,
	`locationSpecialty` 	varchar(255) NOT NULL,
	`locationWard`      	varchar(255) NOT NULL,
	`locationRoomNumber`	varchar(255) NOT NULL,
	`locationBedNumber` 	varchar(255) NOT NULL,
	`statusPtStatus`    	varchar(255) NOT NULL,
	`statusAdmDate`     	varchar(255) NOT NULL,
	`statusAdmTime`     	varchar(255) NOT NULL,
	`statusDcDate`      	varchar(255) NOT NULL,
	`statusDcTime`      	varchar(255) NOT NULL,
	`statusDcNotes`     	varchar(255) NOT NULL,
	`notesAuthorization`	varchar(255) NOT NULL,
	`notesReminderNotes`	varchar(255) NOT NULL,
	`notesEquipment`    	varchar(255) NOT NULL,
	`notesFacility`     	varchar(255) NOT NULL,
	`notesStaff`        	varchar(255) NOT NULL,
	`createdBy`            	int(10) UNSIGNED NOT NULL,
	`createdDate`          	datetime NOT NULL,
	`modifiedBy`           	int(10) UNSIGNED NOT NULL,
	`modifiedDate`         	datetime NOT NULL,
	PRIMARY KEY(`admWorkingId`)
);

DROP TABLE IF EXISTS `adm_submission`;
CREATE TABLE `adm_submission`  ( 
    `submissionId`          int(10) UNSIGNED NOT NULL,
	`admDetailsAdmId`   	int(10) UNSIGNED NOT NULL,
	`ptInfoUniqueId`    	int(10) UNSIGNED NOT NULL,
	`ptInfoConfidential`	varchar(255) NOT NULL,
	`ptInfoCurrentIns`  	varchar(255) NOT NULL,
	`ptInfoDiagnosis`   	varchar(255) NOT NULL,
	`ptInfoAdmNum`      	varchar(255) NOT NULL,
	`admDetailsAdmType` 	varchar(255) NOT NULL,
	`admDetailsDate`    	varchar(255) NOT NULL,
	`admDetailsTime`    	varchar(255) NOT NULL,
	`admDetailsLength`  	varchar(255) NOT NULL,
	`mdAdmitting`       	varchar(255) NOT NULL,
	`mdAttending`       	varchar(255) NOT NULL,
	`mdSurgical`        	varchar(255) NOT NULL,
	`mdPrimary`         	varchar(255) NOT NULL,
	`locationSpecialty` 	varchar(255) NOT NULL,
	`locationWard`      	varchar(255) NOT NULL,
	`locationRoomNumber`	varchar(255) NOT NULL,
	`locationBedNumber` 	varchar(255) NOT NULL,
	`statusPtStatus`    	varchar(255) NOT NULL,
	`statusAdmDate`     	varchar(255) NOT NULL,
	`statusAdmTime`     	varchar(255) NOT NULL,
	`statusDcDate`      	varchar(255) NOT NULL,
	`statusDcTime`      	varchar(255) NOT NULL,
	`statusDcNotes`     	varchar(255) NOT NULL,
	`notesAuthorization`	varchar(255) NOT NULL,
	`notesReminderNotes`	varchar(255) NOT NULL,
	`notesEquipment`    	varchar(255) NOT NULL,
	`notesFacility`     	varchar(255) NOT NULL,
	`notesStaff`        	varchar(255) NOT NULL,
	`createdBy`            	int(10) UNSIGNED NOT NULL,
	`createdDate`          	datetime NOT NULL,
	`modifiedBy`           	int(10) UNSIGNED NOT NULL,
	`modifiedDate`         	datetime NOT NULL,
	PRIMARY KEY(`submissionId`)
);