DROP TABLE IF EXISTS `apt`;
CREATE TABLE `apt`  ( 
	`aptDetailsAptId`      	int(10) UNSIGNED NOT NULL,
	`ptInfoUniqueId`       	int(10) UNSIGNED NOT NULL,
	`ptInfoNewPt`          	varchar(255) NOT NULL,
	`ptInfoCurrentIns`     	varchar(255) NOT NULL,
	`ptInfoAptNum`         	varchar(255) NOT NULL,
	`clinicServiceLocation`	varchar(255) NOT NULL,
	`clinicMd`             	varchar(255) NOT NULL,
	`aptDetailsStartDate`  	varchar(255) NOT NULL,
	`aptDetailsStartTime`  	varchar(255) NOT NULL,
	`aptDetailsLength`     	varchar(255) NOT NULL,
	`aptDetailsAptType`    	varchar(255) NOT NULL,
	`aptDetailsReason`     	varchar(255) NOT NULL,
	`statusPtStatus`       	varchar(255) NOT NULL,
	`statusCheckInDate`    	varchar(255) NOT NULL,
	`statusCheckInTime`    	varchar(255) NOT NULL,
	`statusCheckOutDate`   	varchar(255) NOT NULL,
	`statusCheckOutTime`   	varchar(255) NOT NULL,
	`statusStatusNotes`    	varchar(255) NOT NULL,
	`notesAuthorization`   	varchar(255) NOT NULL,
	`notesReminderNotes`   	varchar(255) NOT NULL,
	`notesEquipment`       	varchar(255) NOT NULL,
	`notesFacility`        	varchar(255) NOT NULL,
	`notesStaff`           	varchar(255) NOT NULL,
	`createdBy`            	int(10) UNSIGNED NOT NULL,
	`createdDate`          	datetime NOT NULL,
	`modifiedBy`           	int(10) UNSIGNED NOT NULL,
	`modifiedDate`         	datetime NOT NULL,
	PRIMARY KEY(`aptDetailsAptId`)
);


DROP TABLE IF EXISTS `apt_working`;
CREATE TABLE `apt_working`  (
    `aptWorkingId`          int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
	`aptDetailsAptId`      	int(10) UNSIGNED NOT NULL,
	`ptInfoUniqueId`       	int(10) UNSIGNED NOT NULL,
	`ptInfoNewPt`          	varchar(255) NOT NULL,
	`ptInfoCurrentIns`     	varchar(255) NOT NULL,
	`ptInfoAptNum`         	varchar(255) NOT NULL,
	`clinicServiceLocation`	varchar(255) NOT NULL,
	`clinicMd`             	varchar(255) NOT NULL,
	`aptDetailsStartDate`  	varchar(255) NOT NULL,
	`aptDetailsStartTime`  	varchar(255) NOT NULL,
	`aptDetailsLength`     	varchar(255) NOT NULL,
	`aptDetailsAptType`    	varchar(255) NOT NULL,
	`aptDetailsReason`     	varchar(255) NOT NULL,
	`statusPtStatus`       	varchar(255) NOT NULL,
	`statusCheckInDate`    	varchar(255) NOT NULL,
	`statusCheckInTime`    	varchar(255) NOT NULL,
	`statusCheckOutDate`   	varchar(255) NOT NULL,
	`statusCheckOutTime`   	varchar(255) NOT NULL,
	`statusStatusNotes`    	varchar(255) NOT NULL,
	`notesAuthorization`   	varchar(255) NOT NULL,
	`notesReminderNotes`   	varchar(255) NOT NULL,
	`notesEquipment`       	varchar(255) NOT NULL,
	`notesFacility`        	varchar(255) NOT NULL,
	`notesStaff`           	varchar(255) NOT NULL,
	`createdBy`             int(10) UNSIGNED NOT NULL,
	`createdDate`           datetime NOT NULL,
	`modifiedBy`            int(10) UNSIGNED NOT NULL,
	`modifiedDate`          datetime NOT NULL,
	PRIMARY KEY(`aptWorkingId`)
);

DROP TABLE IF EXISTS `apt_submission`;
CREATE TABLE `apt_submission`  (
    `submissionId`          int(10) UNSIGNED NOT NULL,
	`aptDetailsAptId`      	int(10) UNSIGNED NOT NULL,
	`ptInfoUniqueId`       	int(10) UNSIGNED NOT NULL,
	`ptInfoNewPt`          	varchar(255) NOT NULL,
	`ptInfoCurrentIns`     	varchar(255) NOT NULL,
	`ptInfoAptNum`         	varchar(255) NOT NULL,
	`clinicServiceLocation`	varchar(255) NOT NULL,
	`clinicMd`             	varchar(255) NOT NULL,
	`aptDetailsStartDate`  	varchar(255) NOT NULL,
	`aptDetailsStartTime`  	varchar(255) NOT NULL,
	`aptDetailsLength`     	varchar(255) NOT NULL,
	`aptDetailsAptType`    	varchar(255) NOT NULL,
	`aptDetailsReason`     	varchar(255) NOT NULL,
	`statusPtStatus`       	varchar(255) NOT NULL,
	`statusCheckInDate`    	varchar(255) NOT NULL,
	`statusCheckInTime`    	varchar(255) NOT NULL,
	`statusCheckOutDate`   	varchar(255) NOT NULL,
	`statusCheckOutTime`   	varchar(255) NOT NULL,
	`statusStatusNotes`    	varchar(255) NOT NULL,
	`notesAuthorization`   	varchar(255) NOT NULL,
	`notesReminderNotes`   	varchar(255) NOT NULL,
	`notesEquipment`       	varchar(255) NOT NULL,
	`notesFacility`        	varchar(255) NOT NULL,
	`notesStaff`           	varchar(255) NOT NULL,
	`createdBy`             int(10) UNSIGNED NOT NULL,
	`createdDate`           datetime NOT NULL,
	`modifiedBy`            int(10) UNSIGNED NOT NULL,
	`modifiedDate`          datetime NOT NULL,
	PRIMARY KEY(`submissionId`)
);

