<?
$stateModel = new Model_State();
$stateModel->select()->query();
$stateOptions = $stateModel->fetchAll();

$prefix = $this->prefix;
$selectedValue = $this->selectedValue;
if (!isset($this->disabled))
    $disabled = 'false';
?>
<? if (strcasecmp($disabled, 'false') == 0) : ?>
<div class="clearfix required select-radio">
    <label for="<?= $prefix; ?>State">State</label>
    <select id="<?= $prefix; ?>State" name="<?= $prefix; ?>State">
        <option value="" <?= ($selectedValue == "0" || $selectedValue == "") ? 'selected="selected"' : '' ?>>Select a State</option>
        <? foreach ($stateOptions as $stateOption): ?>
        <option value="<?= $stateOption['state']; ?>"<?= ($selectedValue == $stateOption['state']) ? 'selected="selected"' : '' ?>><?= $stateOption['desc']; ?></option>
        <? endforeach; ?>
    </select>
	
</div>
<? else : ?>
<div class="clearfix">
    <label for="<?= $prefix; ?>State">State</label>
    <div class="input">
        <?
    if (!count($stateOptions))
    echo '<input disabled="disabled" type="text" id="'.$prefix.'State" name="'.$prefix.'State" value=" " />';
    foreach ($stateOptions as $stateOption)
    if (strcasecmp($stateOption['state'], $selectedValue) == 0 )
    echo '<input disabled="disabled" type="text" id="'.$prefix.'State" name="'.$prefix.'State" value="'.$stateOption['desc'].'" />';
    ?>

    </div>
</div>
<? endif; ?>