    <h1 class="mainPanelHeader weekSelect">
        <a href="#" class="icon">6</a>
        {{cal.dateRange}}
        <a href="#" class="icon">2</a>
    </h1>

    <nav class="tabControls mainPanel" id="patientNav">

    </nav>

    <ul class="calendarHead">
        <li class="headerLabel"></li><li class="columnLabel">Mon 9th</li><li class="columnLabel">Tue 10th</li><li class="columnLabel">Wed 11th</li><li class="columnLabel">Thu 12th</li><li class="columnLabel">Fri 13th</li><li class="columnLabel">Sat 14th</li><li class="columnLabel">Sun 15th</li>
    </ul>

    <div id="calendarContent" class="content"><!-- This is closed in the file that imported it -->

        <div class="alert alert-error" data-alert="alert">

            <a class="close" data-dismiss="alert" href="#">×</a>

            <p><strong>Oh snap!</strong> It seems there was some kind of error.</p>
        </div>

        <!-- Intentionally left blank below -->
        <!-- We now continue with what called this file -->